# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Deploy to github.io
on: [workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
          node-version: '16.x'
          
    - run: cd example
    - name: Install and Build 🔧 
      run: |
        npm ci
        npm run build

    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@4.1.9
      with:
        branch: gh-pages 
        folder: ./build 
